### ISSUE TITLE
Latest iric_dev install yields errors when installing miniconda

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/online_update#22] opened 2021-01-13 23:15 UTC
After updating (using iRIC Maintenance) iRIC crashes when opening previous projects (see #21).

Selected components before selecting everything:
![iric_dev_current](https://user-images.githubusercontent.com/7538707/104521432-1d5f6080-55ba-11eb-93d5-e60968434ea4.png)

As a test I installed everything (selected all components).  I got the following errors:
![iric_dev_miniconda3_error](https://user-images.githubusercontent.com/7538707/104521452-25b79b80-55ba-11eb-8b95-fcd412cec389.png)

This might be because I already had Miniconda installed.  Also, I might have had miniconda running during the install.

I'll do some additional testing and post here if I find anything.

**Comment by kskinoue0612** [comment] 2021-01-19 01:08
Hi Scott,

Thank you for the information.

Actually, I've experienced similar error while installing. In my case, the reason was that I was trying to install Miniconda to path with spaces ("C:\Users\Keisuke Inoue\iRIC_dev"). But looking at the screenshot you've shared, it seems that there is no problem in the path to install. I think it was caused by other reasons, as you've guessed.

I'll try to reproduce the issue. If you've noticed the key to reproduce this, please let me know.

Thank you,

Keisuke

**Comment by kskinoue0612** [comment] 2021-01-19 06:21
Hi Scott,

I've succeeded to reproduce the issue with a PC in my office, and made some modification to the script to install Miniconda, with commit 698fc1a. The issue was fixed with a PC in my office.

Can you test it, when you have time?

Thanks,
Keisuke

**Comment by scharlton2** [comment] 2021-01-19 17:01
On a new machine, that seems to have fixed it but now I'm getting another error when updating:

![image](https://user-images.githubusercontent.com/7538707/105064193-d0f0a680-5a39-11eb-986f-a0a819279189.png)

Pressing Next:

![image](https://user-images.githubusercontent.com/7538707/105064284-e9f95780-5a39-11eb-8fe4-3734e89abacc.png)

It seems to think the newest version is 3.0.19.6708 when it should be 3.0.19.6709.

Note: I tried it again and it seems to work now.

**Comment by scharlton2** [comment] 2021-01-19 17:21
Hi Keisuke,

Have you looked at the [appveyor builds](https://ci.appveyor.com/project/i-RIC/online-update/build/job/nm7u07uu6060ot77)?  It looks like:

https://github.com/i-RIC/online_update/blob/master/dev_src/packages/miniconda/meta/package.xml

didn't get commited; it's still pointing to `installscript.qs` and there are only `installscript_offline.qs` and `installscript_online.qs`.

Thanks,
Scott

**Comment by kskinoue0612** [comment] 2021-01-20 01:16
Hi Scott,

Thank you for the information.

> On a new machine, that seems to have fixed it but now I'm getting another error when updating:
> 
> ![image](https://user-images.githubusercontent.com/7538707/105064193-d0f0a680-5a39-11eb-986f-a0a819279189.png)
> 
> Pressing Next:
> 
> ![image](https://user-images.githubusercontent.com/7538707/105064284-e9f95780-5a39-11eb-8fe4-3734e89abacc.png)
> 
> It seems to think the newest version is 3.0.19.6708 when it should be 3.0.19.6709.
> 
> Note: I tried it again and it seems to work now.

Glad to hear that installing Miniconda on your environment succeeds now!

This morning I've tried updating iRIC GUI to 3.0.19.6709, and it succeeded. From the fact that your retry succeeded, and I succeeded this morning, I guess github was just updating the CDN server, when you've got error.

> Have you looked at the [appveyor builds](https://ci.appveyor.com/project/i-RIC/online-update/build/job/nm7u07uu6060ot77)? It looks like:
> 
> https://github.com/i-RIC/online_update/blob/master/dev_src/packages/miniconda/meta/package.xml
> 
> didn't get commited; it's still pointing to `installscript.qs` and there are only `installscript_offline.qs` and `installscript_online.qs`.

Thanks for your notification, that's true.

When I've built https://github.com/i-RIC/online_update/blob/master/dev/miniconda/4.9.2meta.7z, I've copied installscript_online.qs to installscript.qs before building, so installscript.qs is included in 4.9.2meta.7z. Because of that, installing miniconda succeeds without problems.

Please let me share how I was working on Miniconda.

I've tried to setup Miniconda, so that:

* When installing Miniconda from online update, it download Miniconda installer from iRIC online_update repository, and downloads numpy etc from Anaconda server directly.
* When installing Miniconda from offline installer, Miniconda3 installer and files needed to install numpy are all included in iRIC offline installer, and it does not need internet connection.

To achieve that, I've prepared installscript_online.qs and installscript_offline.qs.
When building offline installer, we can use build_dev_installer.py, as written below.

https://github.com/i-RIC/online_update/blob/master/README.md

Anyway, I agree that it is confusing, so I'm going to make the following modification:

* Copy installscript_online.qs to installscript.qs
* Modify build_dev_installer.py so that there will be less chance for making mistake when building offline installer.

When it's finished, I'm going to make a pull request, and ask you to review.

Sorry that I've not shared information about the work related to Miniconda. I was working on that in "try and error" way. Now I feel it's getting stable, and near to be finished. I'll clean up the code, and share the result.

Thank you,

Keisuke

**Comment by scharlton2** [comment] 2021-01-21 18:30
Hi Keisuke,

Okay, I understand.

Thanks,
Scott

**Closed as completed** 2021-01-23 19:44 UTC
Labels: bug
